### PR TITLE
Finalised Pricing as of the 18th of June

### PR DESCRIPTION
**Pull request by DavideMagno**

### CODE REVIEW

**Comment by DavideMagno** [comment]
Achievements:
I have added the code for calculating the duration of a swap in the SwapPricer code
I finalised the cleaning of the data
I priced the average duration traded for the DTCC report. As agreed this is the 
I started scraping USD data from the SEB website (https://sebgroup.com/our-offering/prospectuses-and-downloads/rates/swap-rates). This will be useful for pricing
Next steps:
Creating a routine that bootstraps the swap curve
Creating a routine to price any DTCC report at any date

**Comment by ThresholdMacro** [comment]
Thanks Davide,
For some reason I have a major conflict in StatusReport.html which is stopping me pulling your changes into GitHub Desktop – as per following screenshot. Shall I a/ ‘use the modified file from main’ or b/ ‘use the modified file’ ?

***@***.***D77573.6504C820]

From: Davide Magno ***@***.***>
Date: Friday, 9 July 2021 at 18:56
To: ThresholdMacro/DTCCdata ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [ThresholdMacro/DTCCdata] Finalised Pricing as of the 18th of June (#3)

Achievements:
I have added the code for calculating the duration of a swap in the SwapPricer code
I finalised the cleaning of the data
I priced the average duration traded for the DTCC report. As agreed this is the
I started scraping USD data from the SEB website (https://sebgroup.com/our-offering/prospectuses-and-downloads/rates/swap-rates). This will be useful for pricing
Next steps:
Creating a routine that bootstraps the swap curve
Creating a routine to price any DTCC report at any date

**Comment by DavideMagno** [comment]
Week 4 - New Milestone: intraday data and other sources of information

**Comment by ThresholdMacro** [comment]
Davide,
Thanks for the latest update – very interesting (still not very comfortable with GitHub, but I seem to be able to pull the code into RStudio, so that’s an improvement!).
Attached is simple histogram of duration by bucket – this is the profile that I’d like to see evolve over time.
Best wishes
Meyrick

From: Davide Magno ***@***.***>
Date: Saturday, 17 July 2021 at 14:44
To: ThresholdMacro/DTCCdata ***@***.***>
Cc: Meyrick Chapman ***@***.***>, Comment ***@***.***>
Subject: Re: [ThresholdMacro/DTCCdata] Finalised Pricing as of the 18th of June (#3)

Week 4 - New Milestone: intraday data and other sources of information

**Comment by DavideMagno** [comment]
Thanks Mayerick - you may have forgotten to attach the histogram? I can't see it

**Comment by ThresholdMacro** [comment]
It was attached my end! Histogram_duration.png

Meyrick Chapman
Hedge Analytics Ltd
________________________________

**Comment by DavideMagno** [comment]
Still no picture Meyrick. Maybe you can try and attach it via email directly?

**Pull request merged**
