### PR TITLE
Add DTCC Reference Guide

### PR DESCRIPTION
**Pull request by DavideMagno**
Meyrick, I have forked the GitHub repository, which means that I have created my version on which I can operate freely. 
Every time I change something, my version of the repository changes. In order for the change to flow to yours, I issue a "pull request" which effectively means "can I share the updates with you"? 

There are two types of pull requests:

- Automatic
- Manual: in this case the new feature will not be added to your repository until they are marked ready for review

I have used the Automatic one for this pull.

Cheers,
Davide

### CODE REVIEW

**Comment by DavideMagno** [comment]
Add the DTCC Reference Guide

**Comment by DavideMagno** [comment]
GitHub has automatically checked that there are no conflicts between what I added (the DTCC Ref Guide) and your repository. You can now merge the pull requests on your side.

**Comment by ThresholdMacro** [comment]
Understood.


From: Davide Magno ***@***.***>
Reply to: ThresholdMacro/DTCCdata ***@***.***>
Date: Tuesday, 22 June 2021 at 07:23
To: ThresholdMacro/DTCCdata ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ThresholdMacro/DTCCdata] Add DTCC Reference Guide (#1)


Meyrick, I have forked the GitHub repository, which means that I have created my version on which I can operate freely.
Every time I change something, my version of the repository changes. In order for the change to flow to yours, I issue a "pull request" which effectively means "can I share the updates with you"?

There are two types of pull requests:

  *   Automatic
  *   Manual: in this case the new feature will not be added to your repository until they are marked ready for review

I have used the Automatic one for this pull.

Cheers,
Davide

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ThresholdMacro/DTCCdata/pull/1

Commit Summary

  *   Add DTCC Reference Guide

File Changes

  *   A RT_PPD_quick_ref_guide.pdf<https://github.com/ThresholdMacro/DTCCdata/pull/1/files#diff-ee8fc933e08acdebd8d13470fc6b3d234d1dc07412c98a5a9fec926560b0482e> (0)

Patch Links:

  *   https://github.com/ThresholdMacro/DTCCdata/pull/1.patch
  *   https://github.com/ThresholdMacro/DTCCdata/pull/1.diff

**Comment by DavideMagno** [comment]
Updates as summarised via email. Please feel free to return with any comment. Those would allow me to improve/change any part of the study.

**Pull request merged**
